# Generated by Django 4.0.4 on 2022-05-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_website', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=30)),
                ('twitter_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('amail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Footer ',
                'verbose_name_plural': 'Footers',
            },
        ),
    ]
