# Generated by Django 4.0.4 on 2022-05-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_descripyion_cv_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='descripion',
            new_name='description',
        ),
    ]
