# Generated by Django 4.0.4 on 2022-05-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_descripion_cv_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
