# Generated by Django 4.0.4 on 2022-05-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_cv_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FQA',
            new_name='FAQ',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
    ]
