# Generated by Django 4.0.4 on 2022-05-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_rename_fqa_faq_alter_faq_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CV',
            new_name='About',
        ),
    ]
