# Generated by Django 4.0.4 on 2022-05-16 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_auto_20220507_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'PropertyBook', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='propertybook',
            options={'verbose_name': 'PropertyBook', 'verbose_name_plural': 'PropertyBooks'},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertyreview',
            options={'verbose_name': 'PropertyReview', 'verbose_name_plural': 'PropertyReviews'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=12000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='propery/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to=settings.AUTH_USER_MODEL, verbose_name='outher'),
        ),
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.CharField(max_length=50, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='children',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='children'),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_from'),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_to'),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='guest',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='guest'),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='property_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='feedback',
            field=models.TextField(default='', max_length=200, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_review', to='property.property', verbose_name='property'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
    ]
