# Generated by Django 4.0.4 on 2022-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_category_options_alter_propertybook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
